ALTER SESSION SET NLS_LANGUAGE= 'HUNGARIAN';
ALTER SESSION SET NLS_TERRITORY= 'HUNGARY';
ALTER SESSION SET NLS_DATE_FORMAT= 'YYYY-MM-DD';
ALTER SESSION SET NLS_DATE_LANGUAGE = 'HUNGARIAN';
ALTER SESSION SET NLS_ISO_CURRENCY = 'HUNGARY';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
ALTER SESSION SET NLS_SORT = 'HUNGARIAN';


ALTER TABLE Lakók ADD CONSTRAINTS p_Lakók PRIMARY KEY (Név,Egészségbiztosítási_szám);
ALTER TABLE Csoportok ADD CONSTRAINTS p_Csoportok PRIMARY KEY (csoport_név,csoportvezető);
ALTER TABLE Házak ADD CONSTRAINTS p_Házak PRIMARY KEY (ház_szám);

ALTER TABLE Lakók ADD CONSTRAINTS f_Lakók_Csoportok FOREIGN KEY (Csoport_név,Csoportvezető)
    REFERENCES Csoportok (csoport_név,csoportvezető);
    
ALTER TABLE Lakók ADD CONSTRAINTS f_Lakók_Házak FOREIGN KEY (ház_szám)
    REFERENCES Házak (ház_szám);

SELECT * FROM nls_session_parameters;